mybatis:
  type-aliases-package: com.xqy.www.domain
  mapper-locations: classpath:/mapper/*.xml
  check-config-location: true

#  mapper-locations=
#  #
#  mybatis.configuration.mapUnderscoreToCamelCase=true
#  #
#  mybatis.configuration.useColumnLabel=true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beauty?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

#mapper.plugin = tk.mybatis.mapper.generator.MapperPlugin
#mapper.Mapper = tk.mybatis.mapper.common.Mapper


